# This is a basic workflow to help you get started with Actions

name: Auto publish release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # Only run the job, if the commit message contains the release trigger.
    if: ${{ contains(github.event.head_commit.message, '#RELEASE') }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo 🤔
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Prepare Release 🧪
        id: prepare_release
        run: |
          message=${{ github.event.head_commit.message }}
          
          RELEASE_DESCRIPTION=$(python ./.github/workflows/get_release_description.py)
          VERSION=$(python ./.github/workflows/publish_release.py --commit_message $message)
          
      - name: Update CHANGELOG ⏱
        uses: stefanzweifel/git-auto-commit-action@v4
        id: update_changelog
        with:
          commit_message: Update CHANGELOG.md
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prepare_release.outputs.VERSION }}
          body: ${{ steps.prepare_release.outputs.RELEASE_DESCRIPTION }}
          release_name: ${{ steps.prepare_release.outputs.VERSION }}
        #  draft: true

